### ISSUE TITLE
Program Crashing using Google

### ISSUE THREAD

**Issue by ImSlick** [Novalys/PokemonGo-Bot-SimpleGUI#92]
The program crashes when it opens a tab in my browser to link Google account. Not sure how to fix it. I'm wanting to use my Google account instead of a Ptc account.

**Comment by Novalys** [comment]
I just used my Google account to login without problems, are you using the compiled program from the releases or the source in visual studio?

**Comment by ImSlick** [comment]
compiled program... I click login, it opens a tab in my browser, then it crashes before I can select which account to use.

**Comment by Novalys** [comment]
Interesting, just a moment let me do some testing without having my Google Account already open in the browser.

**Comment by Novalys** [comment]
Sorry for the late response, I wasn't able to reproduce the problem... but I added a feature to allow you to reset the Google Token now in the login window, could you provide more information about the program crash? any log? or screenshot? That would be really helpful.

**Comment by Moolaned** [comment]
Same problem here. It worked fine on my other Win 7 machine. The program crash when opening the browser in Win 10. Clicking on the Debug button gave this info:

System.Runtime.InteropServices.ExternalException was unhandled
Message: An unhandled exception of type 'System.Runtime.InteropServices.ExternalException' occurred in System.Windows.Forms.dll
Additional information: Requested Clipboard operation did not succeed.

Hope it is useful to you.

**Comment by Novalys** [comment]
It is useful, thanks for the details. I just pushed a possible solution to the problem, could you download the latest source and let me know if that works?

**Comment by Novalys** [comment]
Could someone confirm if the pushed fix worked? So we can close this ticket or keep working on another solution? :smile: thanks!

**Comment by ImSlick** [comment]
I'll give it a try.. will post back.

**Comment by ImSlick** [comment]
I still get a crash: An unhandled exception of type 'System.Runtime.InteropServices.ExternalException' occurred in System.Windows.Forms.dll

It seems it has to do something with it auto copying to my clipboard. I'll check my settings and see if I can fix.

**Comment by memeses** [comment]
Same here, I played for few minutes and the grame crashed. 
![image](https://cloud.githubusercontent.com/assets/20695086/17200547/b0fc10d6-545c-11e6-9e0b-3eac35db11e1.png)

**Comment by memeses** [comment]
The bot dont reboot when crash this way

**Comment by ImSlick** [comment]
I've tried both the source and compiled version. No luck.
